name: Scorecard supply-chain security

on:
  branch_protection_rule:
  schedule:
    - cron: "20 7 * * 2"
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  analysis:
    permissions:
      contents: read
      issues: read
      pull-requests: read
      checks: read
      security-events: write
      id-token: write
    uses: windlasstech/.github/.github/workflows/scorecard-reusable.yml@main
